# Generated by Django 4.0.2 on 2022-02-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('adhar_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Mobile_no', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
