# Generated by Django 4.0.2 on 2022-02-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_pol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='dose',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
