# Generated by Django 4.0.2 on 2022-02-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_pol', '0003_user_data_adhar_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='adhar_card',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
