# Generated by Django 4.0 on 2022-01-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dept', models.IntegerField(choices=[(1, 'CSE'), (2, 'ISE'), (3, 'ECE'), (4, 'CIVIL'), (5, 'MECH')], default=1)),
            ],
        ),
    ]
