# Generated by Django 4.0.2 on 2022-02-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_file', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='Lastname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=150),
        ),
    ]
