# Generated by Django 4.0.2 on 2022-02-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_file', '0002_rename_phone_profile_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Firstname',
            field=models.CharField(max_length=150),
        ),
    ]
