# Generated by Django 4.0 on 2022-02-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_model',
            name='English',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='college_model',
            name='Hindhi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='college_model',
            name='Kannada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='college_model',
            name='Maths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='college_model',
            name='Science',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='college_model',
            name='Social',
            field=models.IntegerField(),
        ),
    ]
