# Generated by Django 4.0 on 2022-02-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_college_model_english_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_model',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
