# Generated by Django 4.0 on 2022-02-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_college_model_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_model',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
