# Generated by Django 4.0 on 2021-12-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Burgerking', '0004_products_prine_alter_products_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prine',
            new_name='price',
        ),
    ]
